// AUTO-GENERATED by scripts/generate-sidebar.mjs — do not edit.
// Source: archive/mkdocs/mkdocs.yml nav

export type GeneratedNavItem = { label: string; slug: string };

export type GeneratedNavSection = {
  title: string;
  groupTitle: string;
  items: GeneratedNavItem[];
};

export const NAV_SECTIONS: GeneratedNavSection[] = [
  {
    "title": "FAQs",
    "groupTitle": "FAQs",
    "items": [
      {
        "label": "Overview",
        "slug": "faq"
      },
      {
        "label": "KVM-over-USB",
        "slug": "faq/kvm-over-usb"
      }
    ]
  },
  {
    "title": "Support",
    "groupTitle": "Support",
    "items": [
      {
        "label": "Support",
        "slug": "support"
      }
    ]
  },
  {
    "title": "Products",
    "groupTitle": "Products",
    "items": [
      {
        "label": "Overview",
        "slug": "products"
      }
    ]
  },
  {
    "title": "KeyMod Series",
    "groupTitle": "KeyMod Series",
    "items": [
      {
        "label": "Overview",
        "slug": "products/keymod"
      },
      {
        "label": "Features",
        "slug": "products/keymod/features"
      },
      {
        "label": "What's In The Box",
        "slug": "products/keymod/whats-in-the-box"
      },
      {
        "label": "How To Connect",
        "slug": "products/keymod/how-to-connect"
      },
      {
        "label": "Use Cases",
        "slug": "products/keymod/use-cases"
      },
      {
        "label": "FAQs",
        "slug": "products/keymod/faq"
      },
      {
        "label": "Reviews",
        "slug": "products/keymod/reviews"
      }
    ]
  },
  {
    "title": "KVM-Go Series",
    "groupTitle": "KVM-Go Series",
    "items": [
      {
        "label": "Overview",
        "slug": "products/kvmgo"
      },
      {
        "label": "Features",
        "slug": "products/kvmgo/features"
      },
      {
        "label": "What's In The Box",
        "slug": "products/kvmgo/whats-in-the-box"
      },
      {
        "label": "How To Connect",
        "slug": "products/kvmgo/how-to-connect"
      },
      {
        "label": "Use Cases",
        "slug": "products/kvmgo/use-cases"
      },
      {
        "label": "Beta Quick Start",
        "slug": "products/kvmgo/beta-quick-start"
      },
      {
        "label": "MicroSD Switch",
        "slug": "products/kvmgo/microsd-switch"
      },
      {
        "label": "FAQs",
        "slug": "products/kvmgo/faq"
      },
      {
        "label": "Reviews",
        "slug": "products/kvmgo/reviews"
      }
    ]
  },
  {
    "title": "Mini-KVM",
    "groupTitle": "Mini-KVM",
    "items": [
      {
        "label": "Overview",
        "slug": "products/minikvm"
      },
      {
        "label": "Features",
        "slug": "products/minikvm/features"
      },
      {
        "label": "What's In The Box",
        "slug": "products/minikvm/whats-in-the-box"
      },
      {
        "label": "How To Connect",
        "slug": "products/minikvm/how-to-connect"
      },
      {
        "label": "USB Switch",
        "slug": "products/minikvm/usb-switch"
      },
      {
        "label": "Extension Pins",
        "slug": "products/minikvm/extension-pins"
      },
      {
        "label": "FAQs",
        "slug": "products/minikvm/faq"
      },
      {
        "label": "Troubleshooting",
        "slug": "products/minikvm/support/mini-kvm-troubleshooting-and-support"
      },
      {
        "label": "Diagnostic (macOS)",
        "slug": "products/minikvm/support/diagnostic-self-check"
      },
      {
        "label": "Diagnostic (Windows)",
        "slug": "products/minikvm/support/diagnostic-self-check-windows"
      },
      {
        "label": "Keyboard and Mouse",
        "slug": "products/minikvm/support/keyboard-mouse-control"
      },
      {
        "label": "Reviews",
        "slug": "products/minikvm/reviews"
      }
    ]
  },
  {
    "title": "uConsole KVM Extension",
    "groupTitle": "uConsole KVM Extension",
    "items": [
      {
        "label": "Overview",
        "slug": "products/kvmext"
      },
      {
        "label": "Features",
        "slug": "products/kvmext/features"
      },
      {
        "label": "What's In The Box",
        "slug": "products/kvmext/whats-in-the-box"
      },
      {
        "label": "Hardware Installation",
        "slug": "products/kvmext/hardware-installation"
      },
      {
        "label": "Software Setup",
        "slug": "products/kvmext/software-setup"
      },
      {
        "label": "Connect to Target",
        "slug": "products/kvmext/connect-to-target"
      },
      {
        "label": "FAQs",
        "slug": "products/kvmext/faq"
      }
    ]
  },
  {
    "title": "Accessories",
    "groupTitle": "Accessories",
    "items": [
      {
        "label": "Overview",
        "slug": "products/accessories"
      },
      {
        "label": "VGA to HDMI Cable 1m",
        "slug": "products/accessories/vga-to-hdmi-cable"
      },
      {
        "label": "Type-C to C Cable Nylon 1.5m",
        "slug": "products/accessories/nylong-c-to-c-150"
      },
      {
        "label": "Type-C to C Cable Orange 1.5m",
        "slug": "products/accessories/type-c-to-c-cable-with-adapter"
      },
      {
        "label": "Type-C to A Cable Black 30cm",
        "slug": "products/accessories/black-c-to-a-30"
      },
      {
        "label": "HDMI Cable 30cm",
        "slug": "products/accessories/hdmi-male-to-male-cable"
      },
      {
        "label": "Toolkit Bag",
        "slug": "products/accessories/openterface-toolkit-bag"
      }
    ]
  },
  {
    "title": "Apps",
    "groupTitle": "Apps",
    "items": [
      {
        "label": "KVM Control",
        "slug": "app/kvm"
      },
      {
        "label": "KeyCmd",
        "slug": "app/keycmd"
      },
      {
        "label": "KVM Control FAQs",
        "slug": "app/kvm/faq"
      },
      {
        "label": "KeyCmd FAQs",
        "slug": "app/keycmd/faq"
      }
    ]
  },
  {
    "title": "KVM Series",
    "groupTitle": "KVM Series",
    "items": [
      {
        "label": "Overview",
        "slug": "tutorial/kvm"
      },
      {
        "label": "Getting Started",
        "slug": "tutorial/kvm/01-getting-started"
      },
      {
        "label": "Basic Operations",
        "slug": "tutorial/kvm/02-basic-operations"
      },
      {
        "label": "Advanced Features",
        "slug": "tutorial/kvm/03-advanced-features"
      },
      {
        "label": "Troubleshooting",
        "slug": "tutorial/kvm/04-troubleshooting"
      }
    ]
  },
  {
    "title": "KeyMod",
    "groupTitle": "KeyMod",
    "items": [
      {
        "label": "Overview",
        "slug": "tutorial/keymod"
      },
      {
        "label": "Getting Started",
        "slug": "tutorial/keymod/01-getting-started"
      },
      {
        "label": "Keyboard & Mouse",
        "slug": "tutorial/keymod/02-keyboard-mouse"
      },
      {
        "label": "Target Keyboard",
        "slug": "tutorial/keymod/03-target-keyboard"
      },
      {
        "label": "Shortcut Hub",
        "slug": "tutorial/keymod/04-shortcuts"
      },
      {
        "label": "Macros",
        "slug": "tutorial/keymod/05-macros"
      },
      {
        "label": "Voice Input",
        "slug": "tutorial/keymod/06-voice-input"
      },
      {
        "label": "AI Integration",
        "slug": "tutorial/keymod/07-ai"
      },
      {
        "label": "Gamepad",
        "slug": "tutorial/keymod/08-gamepad"
      },
      {
        "label": "Numpad",
        "slug": "tutorial/keymod/09-numpad"
      },
      {
        "label": "Presentation",
        "slug": "tutorial/keymod/10-presentation"
      },
      {
        "label": "Settings",
        "slug": "tutorial/keymod/11-settings"
      },
      {
        "label": "Troubleshooting",
        "slug": "tutorial/keymod/12-troubleshooting"
      }
    ]
  },
  {
    "title": "About",
    "groupTitle": "About",
    "items": [
      {
        "label": "Community",
        "slug": "about/community"
      },
      {
        "label": "Multi-Languages",
        "slug": "about/multi-languages"
      },
      {
        "label": "Compliance",
        "slug": "about/compliance"
      },
      {
        "label": "Contribute & Support",
        "slug": "about/contribute-support"
      },
      {
        "label": "Reviews & Media",
        "slug": "about/media"
      },
      {
        "label": "Bulk Orders",
        "slug": "about/bulk_orders"
      },
      {
        "label": "For Enterprise",
        "slug": "about/enterprise"
      },
      {
        "label": "Public Holidays",
        "slug": "about/public-holidays"
      },
      {
        "label": "About Us",
        "slug": "about/about-us"
      }
    ]
  },
  {
    "title": "Policy",
    "groupTitle": "Policy",
    "items": [
      {
        "label": "Overview",
        "slug": "policy"
      },
      {
        "label": "Privacy",
        "slug": "policy/privacy"
      },
      {
        "label": "Terms of Service",
        "slug": "policy/terms-of-service"
      },
      {
        "label": "Return, Refunds & Warranty",
        "slug": "policy/return-refunds-warranty"
      }
    ]
  }
] as const;
