/**
 * Generate src/config/sidebar.generated.ts from archive/mkdocs/mkdocs.yml nav.
 * Run: node scripts/generate-sidebar.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { parse as parseYaml } from 'yaml';

const ROOT = path.resolve(import.meta.dirname, '..');
const MKDOCS = path.join(ROOT, 'archive/mkdocs/mkdocs.yml');
const OUT = path.join(ROOT, 'src/config/sidebar.generated.ts');

function mdPathToSlug(filePath) {
  let p = filePath.replace(/\.md$/, '').replace(/\\/g, '/');
  if (p.endsWith('/index')) p = p.slice(0, -6) || 'index';
  if (p === 'index') return 'index';
  return p;
}

function isDirectLeaf(node) {
  const val = Object.values(node)[0];
  return typeof val === 'string';
}

function isNestedGroup(node) {
  const val = Object.values(node)[0];
  return Array.isArray(val);
}

function collectItems(nodes) {
  const items = [];
  for (const node of nodes) {
    if (isDirectLeaf(node)) {
      const [label, file] = Object.entries(node)[0];
      items.push({ label, slug: mdPathToSlug(file) });
      continue;
    }
    if (isNestedGroup(node)) {
      const [label, children] = Object.entries(node)[0];
      if (children.every(isDirectLeaf)) {
        items.push(...collectItems(children));
      } else {
        for (const child of children) {
          if (isDirectLeaf(child)) items.push(...collectItems([child]));
          else if (isNestedGroup(child)) items.push(...collectItems([child]));
        }
      }
    }
  }
  return items;
}

function sectionsFromNav(nav) {
  const sections = [];

  for (const entry of nav) {
    for (const [topLabel, value] of Object.entries(entry)) {
      if (typeof value === 'string') {
        if (topLabel !== 'Documentation') {
          sections.push({
            title: topLabel,
            groupTitle: topLabel,
            items: [{ label: topLabel, slug: mdPathToSlug(value) }],
          });
        }
        continue;
      }

      if (!Array.isArray(value)) continue;

      const nestedGroups = value.filter(isNestedGroup);
      const directLeaves = value.filter(isDirectLeaf);

      if (directLeaves.length) {
        sections.push({
          title: topLabel,
          groupTitle: topLabel,
          items: collectItems(directLeaves),
        });
      }

      for (const group of nestedGroups) {
        const [groupTitle, children] = Object.entries(group)[0];
        sections.push({
          title: groupTitle,
          groupTitle: groupTitle,
          items: collectItems(children),
        });
      }
    }
  }

  return sections;
}

function loadNav() {
  let raw = fs.readFileSync(MKDOCS, 'utf8');
  raw = raw.replace(/\r\n/g, '\n'); // normalize Windows line endings
  if (raw.startsWith('# AUTO-GENERATED')) {
    raw = raw.split('\n\n').slice(1).join('\n\n');
  }
  const doc = parseYaml(raw, { uniqueKeys: false }) ?? {};
  return doc.nav ?? [];
}

const sections = sectionsFromNav(loadNav());

const body = `// AUTO-GENERATED by scripts/generate-sidebar.mjs — do not edit.
// Source: archive/mkdocs/mkdocs.yml nav

export type GeneratedNavItem = { label: string; slug: string };

export type GeneratedNavSection = {
  title: string;
  groupTitle: string;
  items: GeneratedNavItem[];
};

export const NAV_SECTIONS: GeneratedNavSection[] = ${JSON.stringify(sections, null, 2)} as const;
`;

fs.writeFileSync(OUT, body);
console.log(`Wrote ${sections.length} sidebar sections → ${path.relative(ROOT, OUT)}`);
